### PR TITLE
Added flash nav home profile and login

### LINKED ISSUE #29: User will be able to login to their account (given they enter the correct credentials)

### LINKED ISSUE #30: User will be able to logout

### LINKED ISSUE #31: Basic security rules will be implemented

### LINKED ISSUE #34: User will be able to see their profile

### LINKED ISSUE #35: User will be able to edit their profile

### PR DESCRIPTION
**Pull request by Svampis**

### CODE REVIEW

**Comment by Spencer-Clarke** [comment]
Login page
image

Message when user's account isn't found
image

Message when password is incorrect
image

Saving session and roles
image

**Comment by Svampis** [comment]
Login page
image

**Comment by Svampis** [comment]
User not found message 
image

**Comment by Svampis** [comment]
Incorrect password message
image

**Comment by Svampis** [comment]
Fetching roles and save to session
image

**Comment by Svampis** [comment]
Landing page upon logging in
image

**Comment by Spencer-Clarke** [comment]
Landing on login page after logging out
image

**Comment by Svampis** [comment]
Landing on login page after logging out
image

**Comment by Spencer-Clarke** [comment]
Check if user is logged in
image

**Comment by Svampis** [comment]
Check if user is logged in
image

**Comment by Svampis** [comment]
Redirect from home.php to login.php if user isn't logged in
image

**Comment by Svampis** [comment]
Updatable profile, for example this password change
image

**Comment by Svampis** [comment]
Error message after attempting to change username to one that already exists
image

**Comment by Svampis** [comment]
Email and username validation for updating profile
image

**Comment by Svampis** [comment]
Session destruction upon logging out
image

**Comment by Svampis** [comment]
is_logged_in
image

**Comment by Svampis** [comment]
Invalid current password on profile
image

**Pull request merged**
