### PR TITLE
Feature purchase items

### LINKED ISSUE #77: User will be able to purchase items in their cart

### PR DESCRIPTION
**Pull request by Svampis**

### CODE REVIEW

**Comment by Spencer-Clarke** [comment]
Orders table
image

**Comment by Svampis** [comment]
OrderItems table
image

**Comment by Svampis** [comment]
Checkout Form
image

**Comment by Svampis** [comment]
Check for quantity and sufficient money
image

**Comment by Svampis** [comment]
Orders Table
image

**Comment by Spencer-Clarke** [comment]
Address validation
image

**Comment by Svampis** [comment]
Update products table and cart table
image

**Comment by Svampis** [comment]
Address Validation
image

**Pull request merged**
